services:
  - type: web
    name: subscription-reminder-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI # משתנה סביבה חדש וחיוני
        sync: false
