services:
  - type: web
    name: subscriber-tracking-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_PATH
        value: /tmp/subscriber_tracking.db
      - key: ENABLE_OCR
        value: false
      - key: ENABLE_ANALYTICS
        value: true
      - key: NOTIFICATION_HOUR
        value: 9
      - key: NOTIFICATION_MINUTE
        value: 0
      - key: PORT
        value: 8000
    # Note: TELEGRAM_BOT_TOKEN must be set manually in Render dashboard for security